# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Lunariano
# Description of the Site
description: DJ & Pordutor de Progressive Trance
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://i1.sndcdn.com/visuals-000085450294-BE6BQc-t1240x260.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: lunarianomusic@gmail.com
facebook_username: lunarianomusic
twitter_username: lunarianomusic
instagram_username: lunarianomusic
linkedin_username:
github_username:
youtube_channel_id: UCHlBLYncgdDPVONDLhh7a0g
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Brendon Locatelli
# URL for the Image of the Author
author-image: https://instagram.fbpg1-1.fna.fbcdn.net/v/t51.2885-19/289193857_737257387562625_2475818517473026814_n.jpg
# 60 Words About the Author
author-about: Com grande empenho, LUNARIANO 👨🏻‍🚀 chega decolando nessa jornada, mostrando uma essência autêntica e muita energia nas suas apresentações, onde vem conquistando as pistas e o carinho por onde passa. 🚀
O projeto de Progressive Trance oferece releituras de clássicos da eletrônica, dos Rock & Pop mais consagrados e também de grandes hits atuais, explorando uma vibe de conforto e nostalgia! #LNRNVIBES 🌕
Orbitando o Future Prog, pousa no front com sets agressivos e vaidosamente detalhados. Que vem tocando em eventos pelo centro-oeste, onde, em festival, já dividiu a pista com grandes artistas, como Rica Amaral, Pragmatix e Swarup.
Partindo da base na misteriosa região da Serra do Roncador, comandando a nave está Brendon Locatelli, tendo desde pequeno envolvido com a cultura da música, vem dedicando em desenvolver continuamente sua musicalidade nas mixagens e produções. 🛸atis mauris hendrerit. Sed at vulputate sapien, eget vehicula dolor. Aliquam volutpat pulvinar neque sit amet sodales.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://lunariano.discoporto.com

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
